name: Scrape

on: workflow_dispatch

permissions:
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27'
          go-version-file: 'scraper/go.mod'
      - name: Scrape
        run: |
          cd scraper
          go run . -- --debug > results.json
          cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: eu-west-2
          role-duration-seconds: 900
          mask-aws-account-id: true

      - name: Copy scrape results to S3 bucket
        run: |
          aws s3 cp ./scraper/results.json s3://${{ secrets.S3_BUCKET_NAME }}/data/sources.json