name: Go Test

on:
  push:
    branches:
      - "main"

jobs:
  test_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27'
      - name: Test
        run: |
          if git diff --quiet "${{ github.event.before }}" "${{ github.sha }}" -- scraper/; then
            echo "No changes to scraper"
          else
            echo "Scraper changed, running tests"
            cd scraper
            go test -v ./...
          fi